nginx:
  build: ./nginx/
  ports:
    - 80:80
  links:
    - phpfpm
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./logs/nginx:/var/log/nginx
  volumes_from:
    - project

phpfpm:
  build: ./php/
  ports:
    - 9000:9000
  links:
    - mysql
  volumes:
    - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./logs/php:/var/log/php
  volumes_from:
    - project
  extra_hosts:
    - project.docker.dev:192.168.0.100

project:
  image: alpine:latest
  volumes:
    - ../htdocs:/var/www/htdocs
  command: "true"

mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  volumes:
    - ./databases:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret_password
    MYSQL_DATABASE: project1
    MYSQL_USER: project1
    MYSQL_PASSWORD: a123456

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - 8084:80
  links:
    - phpfpm
    - mysql
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: secret_password
    PMA_HOST: mysql
    PMA_ARBITRARY: 1